# Scrapping Data from a Real Website + Pandas

In [34]:
from bs4 import BeautifulSoup
import requests

In [40]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0'
}

In [35]:
url ='https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

In [41]:
page = requests.get(url, headers=headers)

In [42]:
soup = BeautifulSoup(page.text, 'html.parser')

In [93]:
print(soup.find_all('table'))

[<table class="wikitable sortable">
<caption>
</caption>
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue <br/>(USD millions)
</th>
<th>Revenue growth
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">680,985
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.1%
</td>
<td style="text-align:center;">2,100,000
</td>
<td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
</td>
<td>Retail and cloud computing
</td>
<td style="text-align:center;">637,959
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.0%
</td>
<td style="text-align:center;">1,556,000
</td>
<td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
</td></tr>
<tr>
<td>3
</td>
<td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">400,278
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 7.7%
</td>
<td style="text-align:center;">400,000
</td>
<td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
</td></tr>
<tr>
<td>4
</td>
<td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
</td>
<td>Technology
</td>
<td style="text-align:center;">391,035
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 2.0%
</td>
<td style="text-align:center;">164,000
</td>
<td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">372,809
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.2%
</td>
<td style="text-align:center;">259,500
</td>
<td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">371,433
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.9%
</td>
<td style="text-align:center;">392,400
</td>
<td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
</td></tr>
<tr>
<td>7
</td>
<td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">350,018
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.9%
</td>
<td style="text-align:center;">183,323
</td>
<td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/ExxonMobil" title="ExxonMobil">Exxon Mobil</a>
</td>
<td>Petroleum
</td>
<td style="text-align:center;">349,595
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.5%
</td>
<td style="text-align:center;">60,900
</td>
<td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">308,951
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.7%
</td>
<td style="text-align:center;">48,000
</td>
<td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
</td>
<td>Pharmacy wholesale
</td>
<td style="text-align:center;">293,959
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 12.1%
</td>
<td style="text-align:center;">44,000
</td>
<td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">278,906
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 16.5%
</td>
<td style="text-align:center;">317,233
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Costco" title="Costco">Costco Wholesale</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">254,453
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
</td>
<td style="text-align:center;">333,000
</td>
<td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
</td></tr>
<tr>
<td>13
</td>
<td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
</td>
<td>Health insurance
</td>
<td style="text-align:center;">247,121
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 26.6%
</td>
<td style="text-align:center;">72,398
</td>
<td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
</td></tr>
<tr>
<td>14
</td>
<td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">245,122
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 15.7%
</td>
<td style="text-align:center;">228,000
</td>
<td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">226,827
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.6%
</td>
<td style="text-align:center;">48,411
</td>
<td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron</a>
</td>
<td>Petroleum
</td>
<td style="text-align:center;">202,792
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 0.9%
</td>
<td style="text-align:center;">45,298
</td>
<td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">192,434
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
</td>
<td style="text-align:center;">213,193
</td>
<td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
</td>
<td>Automotive
</td>
<td style="text-align:center;">187,442
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.1%
</td>
<td style="text-align:center;">162,000
</td>
<td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor</a>
</td>
<td>Automotive
</td>
<td style="text-align:center;">184,992
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
</td>
<td style="text-align:center;">171,000
</td>
<td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
</td></tr>
<tr>
<td>20
</td>
<td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">177,011
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 3.3%
</td>
<td style="text-align:center;">103,679
</td>
<td><a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">170,757
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 8.9%
</td>
<td style="text-align:center;">227,855
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>22
</td>
<td><a href="/wiki/Meta_Platforms" title="Meta Platforms">Meta Platforms</a>
</td>
<td>Technology
</td>
<td style="text-align:center;">164,501
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 21.9%
</td>
<td style="text-align:center;">74,067
</td>
<td><a href="/wiki/Menlo_Park,_California" title="Menlo Park, California">Menlo Park, California</a>
</td></tr>
<tr>
<td>23
</td>
<td><a class="mw-redirect" href="/wiki/Centene" title="Centene">Centene</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">163,071
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.9%
</td>
<td style="text-align:center;">60,500
</td>
<td><a href="/wiki/St._Louis" title="St. Louis">St. Louis, Missouri</a>
</td></tr>
<tr>
<td>24
</td>
<td><a class="mw-redirect" href="/wiki/The_Home_Depot" title="The Home Depot">The Home Depot</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">159,514
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.5%
</td>
<td style="text-align:center;">470,100
</td>
<td><a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>
</td></tr>
<tr>
<td>25
</td>
<td><a href="/wiki/Fannie_Mae" title="Fannie Mae">Fannie Mae</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">152,670
</td>

In [24]:
# <table class="wikitable sortable jquery-tablesorter">
# <caption>

In [109]:
soup.find_all('table'[1])

[<a class="mw-jump-link" href="#bodyContent">Jump to content</a>,
 <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a>,
 <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a>,
 <a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a>,
 <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a>,
 <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a>,
 <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a>,
 <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a>,
 <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a>,
 <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a>,
 <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a>,
 <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a>,
 <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]"><span>Special pages</span></a>,
 <a class="mw-logo" href="/wiki/Main_Page">
 <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
 <span class="mw-logo-container skin-invert">
 <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
 <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
 </span>
 </a>,
 <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
 <span>Search</span>
 </a>,
 <a class="" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>,
 <a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>,
 <a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>,
 <a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>,
 <a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a>,
 <a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a>,
 <a class="vector-toc-link" href="#">
 <div class="vector-toc-text">(Top)</div>
 </a>,
 <a class="vector-toc-link" href="#List_of_the_largest_public_/_publicly_traded_companies">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">1</span>
 <span>List of the largest public / publicly traded companies</span>
 </div>
 </a>,
 <a class="vector-toc-link" href="#List_of_largest_private_companies">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">2</span>
 <span>List of largest private companies</span>
 </div>
 </a>,
 <a class="vector-toc-link" href="#List_of_companies_by_profit">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">3</span>
 <span>List of companies by profit</span>
 </div>
 </a>,
 <a class="vector-toc-link" href="#See_also">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">4</span>
 <span>See also</span>
 </div>
 </a>,
 <a class="vector-toc-link" href="#References">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">5</span>
 <span>References</span>
 </div>
 </a>,
 <a class="interlanguage-link-target" data-language-autonym="Deutsch" data-language-local-name="German" data-title="Liste der größten Unternehmen in den Vereinigten Staaten" href="https://de.wikipedia.org/wiki/Liste_der_gr%C3%B6%C3%9Ften_Unternehmen_in_den_Vereinigten_Staaten" hreflang="de" lang="de" title="Liste der größten Unternehmen in den Vereinigten Staaten – German"><span>Deutsch</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="فارسی" data-language-local-name="Persian" data-title="فهرست شرکت‌های آمریکایی" href="https://fa.wikipedia.org/wiki/%D9%81%D9%87%D8%B1%D8%B3%D8%AA_%D8%B4%D8%B1%DA%A9%D8%AA%E2%80%8C%D9%87%D8%A7%DB%8C_%D8%A2%D9%85%D8%B1%DB%8C%DA%A9%D8%A7%DB%8C%DB%8C" hreflang="fa" lang="fa" title="فهرست شرکت‌های آمریکایی – Persian"><span>فارسی</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="Bahasa Indonesia" data-language-local-name="Indonesian" data-title="Daftar perusahaan Amerika Serikat" href="https://id.wikipedia.org/wiki/Daftar_perusahaan_Amerika_Serikat" hreflang="id" lang="id" title="Daftar perusahaan Amerika Serikat – Indonesian"><span>Bahasa Indonesia</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="日本語" data-language-local-name="Japanese" data-title="アメリカ合衆国の企業一覧" href="https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%A1%E3%83%AA%E3%82%AB%E5%90%88%E8%A1%86%E5%9B%BD%E3%81%AE%E4%BC%81%E6%A5%AD%E4%B8%80%E8%A6%A7" hreflang="ja" lang="ja" title="アメリカ合衆国の企業一覧 – Japanese"><span>日本語</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="Nederlands" data-language-local-name="Dutch" data-title="Lijst van Amerikaanse ondernemingen" href="https://nl.wikipedia.org/wiki/Lijst_van_Amerikaanse_ondernemingen" hreflang="nl" lang="nl" title="Lijst van Amerikaanse ondernemingen – Dutch"><span>Nederlands</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="پنجابی" data-language-local-name="Western Punjabi" data-title="امریکی کمپنیان دی لسٹ" href="https://pnb.wikipedia.org/wiki/%D8%A7%D9%85%D8%B1%DB%8C%DA%A9%DB%8C_%DA%A9%D9%85%D9%BE%D9%86%DB%8C%D8%A7%D9%86_%D8%AF%DB%8C_%D9%84%D8%B3%D9%B9" hreflang="pnb" lang="pnb" title="امریکی کمپنیان دی لسٹ – Western Punjabi"><span>پنجابی</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="Português" data-language-local-name="Portuguese" data-title="Lista de maiores empresas dos Estados Unidos por receita" href="https://pt.wikipedia.org/wiki/Lista_de_maiores_empresas_dos_Estados_Unidos_por_receita" hreflang="pt" lang="pt" title="Lista de maiores empresas dos Estados Unidos por receita – Portuguese"><span>Português</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="Română" data-language-local-name="Romanian" data-title="Listă de companii din Statele Unite ale Americii" href="https://ro.wikipedia.org/wiki/List%C4%83_de_companii_din_Statele_Unite_ale_Americii" hreflang="ro" lang="ro" title="Listă de companii din Statele Unite ale Americii – Romanian"><span>Română</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="اردو" data-language-local-name="Urdu" data-title="امریکی کمپنیوں کی فہرست" href="https://ur.wikipedia.org/wiki/%D8%A7%D9%85%D8%B1%DB%8C%DA%A9%DB%8C_%DA%A9%D9%85%D9%BE%D9%86%DB%8C%D9%88%DA%BA_%DA%A9%DB%8C_%D9%81%DB%81%D8%B1%D8%B3%D8%AA" hreflang="ur" lang="ur" title="امریکی کمپنیوں کی فہرست – Urdu"><span>اردو</span></a>,
 <a class="wbc-editpage" href="https://www.wikidata.org/wiki/Special:EntityPage/Q1860802#sitelinks-wikipedia" title="Edit interlanguage links">Edit links</a>,
 <a accesskey="c" href="/wiki/List_of_largest_companies_in_the_United_States_by_revenue" title="View the content page [c]"><span>Article</span></a>,
 <a accesskey="t" href="/wiki/Talk:List_of_largest_companies_in_the_United_States_by_revenue" rel="discussion" title="Discuss improvements to the content page [t]"><span>Talk</span></a>,
 <a href="/wiki/List_of_largest_companies_in_the_United_States_by_revenue"><span>Read</span></a>,
 <a accesskey="e" href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" title="Edit this page [e]"><span>Edit</span></a>,
 <a accesskey="h" href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=history" title="Past revisions of this page [h]"><span>View history</span></a>,
 <a href="/wiki/List_of_largest_companies_in_the_United_States_by_revenue"><span>Read</span></a>,
 <a accesskey="e" href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" title="Edit this page [e]"><span>Edit</span></a>,
 <a href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=history"><span>View history</span></a>,
 <a accesskey="j" href="/wiki/Special:WhatLinksHere/List_of_largest_companies_in_the_United_States_by_revenue" title="List of all English Wikipedia pages containing links to this page [j]"><span>What links here</span></a>,
 <a accesskey="k" href="/wiki/Special:RecentChangesLinked/List_of_largest_companies_in_the_United_States_by_revenue" rel="nofollow" title="Recent changes in pages linked from this page [k]"><span>Related changes</span></a>,
 <a accesskey="u" href="//en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard" title="Upload files [u]"><span>Upload file</span></a>,
 <a href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;oldid=1343833769" title="Permanent link to this revision of this page"><span>Permanent link</span></a>,
 <a href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=info" title="More information about this page"><span>Page information</span></a>,
 <a href="/w/index.php?title=Special:CiteThisPage&amp;page=List_of_largest_companies_in_the_United_States_by_revenue&amp;id=1343833769&amp;wpFormIdentifier=titleform" title="Information on how to cite this page"><span>Cite this page</span></a>,
 <a href="/w/index.php?title=Special:UrlShortener&amp;url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FList_of_largest_companies_in_the_United_States_by_revenue"><span>Get shortened URL</span></a>,
 <a href="/w/index.php?title=Special:DownloadAsPdf&amp;page=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=show-download-screen" title="Download this page as a PDF file"><span>Download as PDF</span></a>,
 <a accesskey="p" href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;printable=yes" title="Printable version of this page [p]"><span>Printable version</span></a>,
 <a href="https://commons.wikimedia.org/wiki/Category:Companies_of_the_United_States" hreflang="en"><span>Wikimedia Commons</span></a>,
 <a accesskey="g" href="https://www.wikidata.org/wiki/Special:EntityPage/Q1860802" title="Structured data on this page hosted by Wikidata [g]"><span>Wikidata item</span></a>,
 <a href="/wiki/United_States" title="United States">United States</a>,
 <a href="/wiki/Revenue" title="Revenue">revenue</a>,
 <a href="/wiki/Fortune_500" title="Fortune 500"><i>Fortune</i> 500</a>,
 <a href="/wiki/Forbes" title="Forbes">Forbes</a>,
 <a href="/wiki/List_of_public_corporations_by_market_capitalization" title="List of public corporations by market capitalization">publicly traded companies</a>,
 <a href="/wiki/Tax_inversion" title="Tax inversion">tax inversion</a>,
 <a href="/wiki/Government-sponsored_enterprise" title="Government-sponsored enterprise">government-sponsored enterprises</a>,
 <a href="/wiki/United_States_Congress" title="United States Congress">Congress</a>,
 <a href="/wiki/Privately_held_company" title="Privately held company">privately held companies</a>,
 <a href="/wiki/Cargill" title="Cargill">Cargill</a>,
 <a class="mw-redirect" href="/wiki/Koch_Industries" title="Koch Industries">Koch Industries</a>,
 <a href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit&amp;section=1" title="Edit section: List of the largest public / publicly traded companies"><span>edit</span></a>,
 <a href="/wiki/Fiscal_year" title="Fiscal year">fiscal year</a>,
 <a href="/wiki/Fortune_500" title="Fortune 500"><i>Fortune</i> 500</a>,
 <a href="#cite_note-:0-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a>,
 <a class="mw-redirect" href="/wiki/Aerospace_and_defense_industry" title="Aerospace and defense industry">Aerospace and defense</a>,
 <a class="mw-redirect" href="/wiki/Agriculture_manufacturing" title="Agriculture manufacturing">agriculture manufacturing</a>,
 <a class="mw-redirect" href="/wiki/Airline_industry" title="Airline industry">airline</a>,
 <a href="/wiki/Automotive_industry" title="Automotive industry">automotive</a>,
 <a class="mw-redirect" href="/wiki/Beverage_industry" title="Beverage industry">beverage</a>,
 <a href="/wiki/Conglomerate_(company)" title="Conglomerate (company)">conglomerate</a>,
 <a href="/wiki/Energy_industry" title="Energy industry">energy</a>,
 <a class="mw-redirect" href="/wiki/Financial_industry" title="Financial industry">financials</a>,
 <a href="/wiki/Food_industry" title="Food industry">food industry and food processing</a>,
 <a class="mw-redirect" href="/wiki/Health_insurance_industry" title="Health insurance industry">health insurance</a>,
 <a href="/wiki/Healthcare_industry" title="Healthcare industry">healthcare</a>,
 <a class="mw-redirect" href="/wiki/Information_technology_industry" title="Information technology industry">information technology</a>,
 <a class="mw-redirect" href="/wiki/Insurance_industry" title="Insurance industry">insurance</a>,
 <a href="/wiki/Machine_industry" title="Machine industry">machinery</a>,
 <a class="mw-redirect" href="/wiki/Media_industry" title="Media industry">media</a>,
 <a href="/wiki/Petroleum_industry" title="Petroleum industry">petroleum</a>,
 <a href="/wiki/Pharmaceutical_industry" title="Pharmaceutical industry">pharmaceutical and pharmacy wholesale</a>,
 <a href="/wiki/Retail_industry" title="Retail industry">retail</a>,
 <a class="mw-redirect" href="/wiki/Technology_industry" title="Technology industry">technology</a>,
 <a href="/wiki/Telecommunications_industry" title="Telecommunications industry">telecommunications</a>,
 <a class="mw-redirect" href="/wiki/Telecom_hardware_manufacturing" title="Telecom hardware manufacturing">telecom hardware manufacturing</a>,
 <a class="mw-redirect" href="/wiki/Transportation_industry" title="Transportation industry">transportation</a>,
 <a href="#cite_note-:0-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Walmart" title="Walmart">Walmart</a>,
 <a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>,
 <a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>,
 <a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>,
 <a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>,
 <a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>,
 <a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>,
 <a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>,
 <a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>,
 <a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>,
 <a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>,
 <a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>,
 <a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>,
 <a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>,
 <a href="/wiki/ExxonMobil" title="ExxonMobil">Exxon Mobil</a>,
 <a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>,
 <a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>,
 <a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>,
 <a href="/wiki/Cencora" title="Cencora">Cencora</a>,
 <a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>,
 <a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City, New York</a>,
 <a href="/wiki/Costco" title="Costco">Costco Wholesale</a>,
 <a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>,
 <a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>,
 <a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>,
 <a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>,
 <a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>,
 <a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>,
 <a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>,
 <a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron</a>,
 <a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>,
 <a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>,
 <a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>,
 <a href="/wiki/General_Motors" title="General Motors">General Motors</a>,
 <a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>,
 <a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor</a>,
 <a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>,
 <a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>,
 <a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>,
 <a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City, New York</a>,
 <a href="/wiki/Meta_Platforms" title="Meta Platforms">Meta Platforms</a>,
 <a href="/wiki/Menlo_Park,_California" title="Menlo Park, California">Menlo Park, California</a>,
 <a class="mw-redirect" href="/wiki/Centene" title="Centene">Centene</a>,
 <a href="/wiki/St._Louis" title="St. Louis">St. Louis, Missouri</a>,
 <a class="mw-redirect" href="/wiki/The_Home_Depot" title="The Home Depot">The Home Depot</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>,
 <a href="/wiki/Fannie_Mae" title="Fannie Mae">Fannie Mae</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington, D.C.</a>,
 <a href="/wiki/Walgreens_Boots_Alliance" title="Walgreens Boots Alliance">Walgreens Boots Alliance</a>,
 <a href="/wiki/Deerfield,_Illinois" title="Deerfield, Illinois">Deerfield, Illinois</a>,
 <a href="/wiki/Kroger" title="Kroger">Kroger</a>,
 <a href="/wiki/Cincinnati" title="Cincinnati">Cincinnati, Ohio</a>,
 <a href="/wiki/Phillips_66" title="Phillips 66">Phillips 66</a>,
 <a href="/wiki/Houston" title="Houston">Houston, Texas</a>,

In [110]:
soup.find('table',class_ = 'wikitable sortable')

<table class="wikitable sortable">
<caption>
</caption>
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue <br/>(USD millions)
</th>
<th>Revenue growth
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">680,985
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.1%
</td>
<td style="text-align:center;">2,100,000
</td>
<td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>
</td>
<td>Retail and cloud computing
</td>
<td style="text-align:center;">637,959
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.0%
</td>
<td style="text-align:center;">1,556,000
</td>
<td><a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>
</td></tr>
<tr>
<td>3
</td>
<td><a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">400,278
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 7.7%
</td>
<td style="text-align:center;">400,000
</td>
<td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
</td></tr>
<tr>
<td>4
</td>
<td><a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>
</td>
<td>Technology
</td>
<td style="text-align:center;">391,035
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 2.0%
</td>
<td style="text-align:center;">164,000
</td>
<td><a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">372,809
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.2%
</td>
<td style="text-align:center;">259,500
</td>
<td><a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">371,433
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.9%
</td>
<td style="text-align:center;">392,400
</td>
<td><a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>
</td></tr>
<tr>
<td>7
</td>
<td><a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">350,018
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 13.9%
</td>
<td style="text-align:center;">183,323
</td>
<td><a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/ExxonMobil" title="ExxonMobil">Exxon Mobil</a>
</td>
<td>Petroleum
</td>
<td style="text-align:center;">349,595
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 1.5%
</td>
<td style="text-align:center;">60,900
</td>
<td><a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">308,951
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.7%
</td>
<td style="text-align:center;">48,000
</td>
<td><a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cencora" title="Cencora">Cencora</a>
</td>
<td>Pharmacy wholesale
</td>
<td style="text-align:center;">293,959
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 12.1%
</td>
<td style="text-align:center;">44,000
</td>
<td><a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">278,906
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 16.5%
</td>
<td style="text-align:center;">317,233
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Costco" title="Costco">Costco Wholesale</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">254,453
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
</td>
<td style="text-align:center;">333,000
</td>
<td><a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>
</td></tr>
<tr>
<td>13
</td>
<td><a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>
</td>
<td>Health insurance
</td>
<td style="text-align:center;">247,121
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 26.6%
</td>
<td style="text-align:center;">72,398
</td>
<td><a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>
</td></tr>
<tr>
<td>14
</td>
<td><a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>
</td>
<td>Technology and cloud computing
</td>
<td style="text-align:center;">245,122
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 15.7%
</td>
<td style="text-align:center;">228,000
</td>
<td><a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">226,827
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 10.6%
</td>
<td style="text-align:center;">48,411
</td>
<td><a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron</a>
</td>
<td>Petroleum
</td>
<td style="text-align:center;">202,792
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 0.9%
</td>
<td style="text-align:center;">45,298
</td>
<td><a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">192,434
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span><span data-sort-value="7000300000000000000♠" style="display:none"></span> 11.9%
</td>
<td style="text-align:center;">213,193
</td>
<td><a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/General_Motors" title="General Motors">General Motors</a>
</td>
<td>Automotive
</td>
<td style="text-align:center;">187,442
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 9.1%
</td>
<td style="text-align:center;">162,000
</td>
<td><a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor</a>
</td>
<td>Automotive
</td>
<td style="text-align:center;">184,992
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.0%
</td>
<td style="text-align:center;">171,000
</td>
<td><a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>
</td></tr>
<tr>
<td>20
</td>
<td><a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">177,011
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 3.3%
</td>
<td style="text-align:center;">103,679
</td>
<td><a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">170,757
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 8.9%
</td>
<td style="text-align:center;">227,855
</td>
<td><a href="/wiki/New_York_City" title="New York City">New York City, New York</a>
</td></tr>
<tr>
<td>22
</td>
<td><a href="/wiki/Meta_Platforms" title="Meta Platforms">Meta Platforms</a>
</td>
<td>Technology
</td>
<td style="text-align:center;">164,501
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 21.9%
</td>
<td style="text-align:center;">74,067
</td>
<td><a href="/wiki/Menlo_Park,_California" title="Menlo Park, California">Menlo Park, California</a>
</td></tr>
<tr>
<td>23
</td>
<td><a class="mw-redirect" href="/wiki/Centene" title="Centene">Centene</a>
</td>
<td>Healthcare
</td>
<td style="text-align:center;">163,071
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.9%
</td>
<td style="text-align:center;">60,500
</td>
<td><a href="/wiki/St._Louis" title="St. Louis">St. Louis, Missouri</a>
</td></tr>
<tr>
<td>24
</td>
<td><a class="mw-redirect" href="/wiki/The_Home_Depot" title="The Home Depot">The Home Depot</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">159,514
</td>
<td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 4.5%
</td>
<td style="text-align:center;">470,100
</td>
<td><a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>
</td></tr>
<tr>
<td>25
</td>
<td><a href="/wiki/Fannie_Mae" title="Fannie Mae">Fannie Mae</a>
</td>
<td>Financials
</td>
<td style="text-align:center;">152,670
</td>

In [111]:
table =soup.find_all('table')[1]

In [112]:
print(table)

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue <br/>(USD billions)
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/Cargill" title="Cargill">Cargill</a>
</td>
<td>Food &amp; Drink
</td>
<td style="text-align:center;">154
</td>
<td style="text-align:center;">155,000
</td>
<td><a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>
</td></tr>
<tr>
<td>2
</td>
<td><a class="mw-redirect" href="/wiki/Koch_Industries" title="Koch Industries">Koch</a>
</td>
<td>Multicompany
</td>
<td style="text-align:center;">125
</td>
<td style="text-align:center;">120,000
</td>
<td><a href="/wiki/Wichita,_Kansas" title="Wichita, Kansas">Wichita, Kansas</a>
</td></tr>
<tr>
<td>3
</td>
<td><a class="mw-redirect" href="/wiki/Publix_Super_Markets" title="Publix Super Markets">Publix Super Markets</a>
</td>
<td>Food Markets
</td>
<td style="text-align:center;">59.7
</td>
<td style="text-align:center;">260,000
</td>
<td><a href="/wiki/Lakeland,_Florida" title="Lakeland, Florida">Lakeland, Florida</a>
</td></tr>
<tr>
<td>4
</td>
<td><a class="mw-redirect" href="/wiki/Mars,_Incorporated" title="Mars, Incorporated">Mars</a>
</td>
<td>Food &amp; Drink
</td>
<td style="text-align:center;">55
</td>
<td style="text-align:center;">150,000
</td>
<td><a href="/wiki/McLean,_Virginia" title="McLean, Virginia">McLean, Virginia</a>
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/H-E-B" title="H-E-B">H-E-B Grocery Company</a>
</td>
<td>Food Markets
</td>
<td style="text-align:center;">49.57
</td>
<td style="text-align:center;">175,000
</td>
<td><a class="mw-redirect" href="/wiki/San_Antonio,_Texas" title="San Antonio, Texas">San Antonio, Texas</a>
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Reyes_Holdings" title="Reyes Holdings">Reyes Holdings</a>
</td>
<td>Food, Drink &amp; Tobacco
</td>
<td style="text-align:center;">44
</td>
<td style="text-align:center;">36,000
</td>
<td><a href="/wiki/Rosemont,_Illinois" title="Rosemont, Illinois">Rosemont, Illinois</a>
</td></tr>
<tr>
<td>7
</td>
<td><a class="mw-redirect" href="/wiki/Enterprise_Mobility" title="Enterprise Mobility">Enterprise Mobility</a>
</td>
<td>Services
</td>
<td style="text-align:center;">38
</td>
<td style="text-align:center;">100,000
</td>
<td><a href="/wiki/Clayton,_Missouri" title="Clayton, Missouri">Clayton, Missouri</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/Fidelity_Investments" title="Fidelity Investments">Fidelity Investments</a>
</td>
<td>Insurance
</td>
<td style="text-align:center;">32.7
</td>
<td style="text-align:center;">78,000
</td>
<td><a href="/wiki/Boston" title="Boston">Boston, Massachusetts</a>
</td></tr>
<tr>
<td>9
</td>
<td><a href="/wiki/Southern_Glazer%27s_Wine_and_Spirits" title="Southern Glazer's Wine and Spirits">Southern Glazer's Wine &amp; Spirits</a>
</td>
<td>Food, Drink &amp; Tobacco
</td>
<td style="text-align:center;">25
</td>
<td style="text-align:center;">24,000
</td>
<td><a href="/wiki/Miramar,_Florida" title="Miramar, Florida">Miramar, Florida</a>
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cox_Enterprises" title="Cox Enterprises">Cox Enterprises</a>
</td>
<td>Media
</td>
<td style="text-align:center;">23.5
</td>
<td style="text-align:center;">50,000
</td>
<td><a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>
</td></tr></tbody></table>

In [113]:
world_titles = table.find_all('th')

In [114]:
world_titles

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue <br/>(USD billions)
 </th>,
 <th>Employees
 </th>,
 <th>Headquarters
 </th>]

In [115]:
world_table_titles = [title.text.strip() for title in world_titles]
# print(world_table_titles)

In [116]:
print(world_table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD billions)', 'Employees', 'Headquarters']

In [117]:
import pandas as pd

In [118]:
df = pd.DataFrame(columns = world_table_titles)

df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD billions), Employees, Headquarters]
Index: []

In [119]:
column_data = table.find_all('tr')

In [124]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

In [125]:
df

,Rank,Name,Industry,Revenue (USD billions),Employees,Headquarters
0,1,Cargill,Food & Drink,154,"155,000","Minnetonka, Minnesota"
1,2,Koch,Multicompany,125,"120,000","Wichita, Kansas"
2,3,Publix Super Markets,Food Markets,59.7,"260,000","Lakeland, Florida"
3,4,Mars,Food & Drink,55,"150,000","McLean, Virginia"
4,5,H-E-B Grocery Company,Food Markets,49.57,"175,000","San Antonio, Texas"
5,6,Reyes Holdings,"Food, Drink & Tobacco",44,"36,000","Rosemont, Illinois"
6,7,Enterprise Mobility,Services,38,"100,000","Clayton, Missouri"
7,8,Fidelity Investments,Insurance,32.7,"78,000","Boston, Massachusetts"
8,9,Southern Glazer's Wine & Spirits,"Food, Drink & Tobacco",25,"24,000","Miramar, Florida"
9,10,Cox Enterprises,Media,23.5,"50,000","Atlanta, Georgia"

In [126]:
df.to_csv(r'C:\Python Practice\companies.csv',index = False)

In [122]:
print(individual_row_data)

['10', 'Cox Enterprises', 'Media', '23.5', '50,000', 'Atlanta, Georgia']